apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app: database
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.database.service.type }}
  selector:
    app: database
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.database.service.port }}
    targetPort: {{ .Values.database.service.port }}
    name: mysql
  clusterIP: None